#For more details
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
#Be sure to check the docs
#
#Format
#- type: | markdown | textarea | input | checkboxes |
#  id:   | just an id, no actual relevance |
#  attributes:
#    label:       | Box title |
#    description: | Box small text - Description |
#
name: Feature Request
#title: "[Bug]: " | if you want to have a have it automatically say [Bug] when they start the form
description: Suggest an idea for this project. If this doesn't look right
#labels: [Bug] | Auto labels the post, as we do not use this, commenting out, purely as reference

body:
- type: markdown
  id: Feature-Forum
  attributes:
    value: "**Feature Requests are on forums <br> Please place all features requests here: https://www.paradisestation.org/forum/60-suggestions/"
- type: textarea
  id: Go-Forum-PLEASE
  attributes:
    label: Visit forum
    description: https://www.paradisestation.org/forum/60-suggestions/
    placeholder: Please place all features requests here | https://www.paradisestation.org/forum/60-suggestions/
